
name: CI

on:
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Update the version
        run: |
          git config user.email "contact.actions.team@example.com"
          git config user.name "Actions"
          git rev-parse HEAD > version
          git commit -am "Updating version file"
          git push

      - name: Zip the contents
        run: |
          zip -r diagnostic-script-`cat version`.zip *.py
  
      - name: Tag the commit
        run: |
          tag=$(date +"%Y.%m.%d.%H.%M.%S")
          git tag $tag
          git push origin $tag
          echo "GITHUB_SHA_SHORT=$tag" >> $GITHUB_ENV

      - name: Release the new script
        uses: actions/create-release@v1.1.4

        # prevent releases from workflows run manually from branches other than main
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.GITHUB_SHA_SHORT }}
          release_name: Release ${{ env.GITHUB_SHA_SHORT }}
          body: |
            Automated release
          draft: false
          prerelease: false

